- name: Destroy VM
  community.libvirt.virt:
    name: "{{ instance.name }}"
    command: destroy
    uri: "{{ qemu_session }}"
  tags: destroy_kvm_vm

- name: Undefine VM
  community.libvirt.virt:
    name: "{{ instance.name }}"
    command: undefine
    uri: "{{ qemu_session }}"
  tags: destroy_kvm_vm

- name: Remove qcow image
  ansible.builtin.file:
    path: "{{ libvirt_image_dir }}/{{ instance.name }}.qcow2"
    state: absent
  tags: destroy_kvm_vm
